### ISSUE TITLE
Add build instructions to README.md

### ISSUE THREAD

**Issue by jayjaybillings** [doecode/client#1]
@twelsch1 Will you please add a few lines of build instructions to the README.md file?

**Comment by twelsch1** [comment]
I've added the steps.  NPM update ensures that all the packages are up to date. It only needs to be run when packages are updated. The command "npm run deploy" then runs it.

Currently, because of the reliance on the API for validation it is coupled to the DOE Code server. The local settings expect the server to be running at localhost:8080. You'll want to deploy that first, then when you enter the "npm run deploy" command it will automatically move to the next port of 8081.

**Comment by jayjaybillings** [comment]
Got it. Thanks!
