### ISSUE TITLE
Re-styling the client CSS

### ISSUE THREAD

**Issue by jayjaybillings** [doecode/client#3]
We're in the process of creating an ORNL-branded deployment of DOE CODE. However, it isn't clear to me whether I should edit style information in doecode.css or doecode.js. Any notes on changing styles? I get the impression based on the main HTML file that doecode.css is not actually called and that the CSS is generated from the Javascript. Any help is appreciated!

**Comment by andrewsmith4814** [comment]
The current version of master can get a little unclear. Ideally, it'll be simplified with the next production release (fingers crossed).
There are 3 doecode css files, separated mainly for the sake of organization. There is a css file just for font includes, (mainly because there are so many different fonts, and because my IDE kept tripping up its css validator on them), the main css file that defines all of our custom content, and a css file for media queries. 
At build time, the maven minify plugin takes all 3 of those files (and the css files from various libraries), and minifies them into one css file. In an attempt to reduce render blocking, I made a bit of an abnormal decision with the css. What it does, on init, the application reads the contents of the css file into a string. That string is then compiled into the mustache template, inside of a style block in the "head-content" template.
In the next production release, if all modifications go as planned, the minified css file will be released as normal. Certain libraries will actually be included with normal <link href='.....'/> calls, just at the bottom with the javascript includes. This will be our measure against render blocking that doesn't involve writing into a style block in the header. 
So, to answer your question, just editing doecode-media-queries.css or doecode.css will do the trick. We're only using the javascript (with the exception of the input form) to bind events to buttons and such.

**Comment by jayjaybillings** [comment]
Okay, thanks Andrew. I'll give it a go.


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by andrewsmith4814** [comment]
I figured I'd follow up here. doecode-css.css is now included in the header as file, instead of just writing markup directly into the webpage. In the release coming out today, it's a minified aggregate of the hand-written css we have, and bootstrap. Other css libraries are now included in the bottom, in the footer. It was the best solution we could come up with to raise our google pagespeed score.
